db:
  type: "postgres"
  port: 5432
  database: "postgres"

server:
  #host: "localhost"
  port: 3000

AiServer:
  host: "127.0.0.1" #"localhost"
  port: 5001

jwt:
  expiresIn: 36000 # 60 * 60s

image:
  filesize: 5242880 # 5MB
